---
- name: ensure openldap-clients is at the latest version
  yum: pkg=openldap-clients state=latest

- name: ensure sssd is at the latest version
  yum: pkg=sssd state=latest

- name: ensure sssd-client is at the latest version
  yum: pkg=sssd-client state=latest

- name: ensure krb5-workstation is at the latest version
  yum: pkg=krb5-workstation state=latest

- name: ensure oddjob is at the latest version
  yum: pkg=oddjob state=latest

- name: ensure oddjob-mkhomedir is at the latest version
  yum: pkg=oddjob-mkhomedir state=latest

- name: create ldap ca certs directory
  file: path=/etc/openldap/cacerts state=directory owner=root group=root

- name: copy Active Directory CA cert
  copy: src=AD-CA.cer dest=/etc/openldap/cacerts owner=root group=root
  notify:
    - run cacertdir_rehash on ldap cacerts

- name: configure krb5.conf
  template: src=krb5.conf.j2 dest=/etc/krb5.conf owner=root group=root mode=0644

- name: copy keytab to client
  copy: src={{ ansible_hostname }}.keytab dest=/etc/krb5.keytab owner=root group=root mode=0640

- name: test if mkhomedir enabled
  command: "egrep pam_oddjob_mkhomedir.so /etc/pam.d/system-auth"
  register: mkhomedir_result
  ignore_errors: True

- name: enable mkhomedir
  command: "authconfig --enablesssd --enablesssdauth  --enablemkhomedir --disableldap --disableldapauth --disablekrb5 --update"
  when: mkhomedir_result|failed

- name: configure sssd.conf
  template: src=sssd.conf.j2 dest=/etc/sssd/sssd.conf owner=root group=root mode=0400
  notify:
    - restart sssd

